/** Portfolio projects seed — keep in sync with create-space/src/data/defaultWorks.ts */

export const worksDefaults = [
  {
    id: "work-travelodeal",
    title: "Travelodeal UK",
    category: "Travel",
    url: "https://www.travelodeal.co.uk/",
    tech: ["Next.js", "React.js", "Node.js", "Express.js", "TypeScript", "REST APIs", "AWS", "DevOps"],
    description:
      "Travel-domain product for the UK market—holiday discovery, offers, and booking-oriented flows. Work spans the full stack and cloud delivery for a live production travel platform.",
    features: [
      "Travel & holiday-focused customer journeys",
      "Modern React / Next.js frontend with scalable APIs",
      "Cloud-hosted deployment and DevOps practices",
      "Performance-oriented delivery for a public travel site",
    ],
    imageUrl: "",
  },
  {
    id: "work-punya",
    title: "Punya Autowheels Platform",
    category: "Automobile",
    url: "https://www.punyaautowheels.com/",
    tech: ["React.js", "Node.js", "Express.js", "MySQL", "AWS"],
    description:
      "Full-scale digital platform for an automobile dealership — vehicle showcasing, customer inquiries, and lead management with SEO-optimized architecture.",
    features: [
      "Dynamic vehicle listing with detailed specifications",
      "Lead generation system with inquiry tracking",
      "SEO-optimized architecture for higher search visibility",
      "Scalable backend APIs for handling user requests",
    ],
    imageUrl: "",
  },
  {
    id: "work-vikramshila",
    title: "Vikramshila Automobiles",
    category: "Automobile",
    url: "https://www.vikramshilaautomobiles.com/",
    tech: ["React.js", "Next.js", "Node.js"],
    description: "High-performance dealership website focused on customer engagement and conversion.",
    features: [
      "Structured vehicle catalog with detailed views",
      "Integrated inquiry and contact system",
      "Optimized frontend rendering for performance",
      "Mobile-first responsive design",
    ],
    imageUrl: "",
  },
  {
    id: "work-vinfast",
    title: "Patliputra VinFast",
    category: "EV",
    url: "https://patliputravinfast.in/",
    tech: ["Next.js", "React.js", "REST APIs"],
    description: "Modern EV dealership platform promoting electric mobility through an engaging interface.",
    features: ["EV product showcase", "Lead capture system", "High-performance Next.js rendering", "Clean minimal design"],
    imageUrl: "",
  },
  {
    id: "work-patliputra-group",
    title: "Patliputra Group",
    category: "Corporate",
    url: "https://patliputragroup.com/",
    tech: ["React.js", "Node.js"],
    description: "Corporate website representing multiple business verticals under one umbrella.",
    features: ["Multi-business layout", "SEO-friendly architecture", "Clean navigation", "Scalable frontend"],
    imageUrl: "",
  },
  {
    id: "work-nanak",
    title: "Nanak Accountants",
    category: "Finance",
    url: "https://nanakaccountants.com.au/",
    tech: ["Next.js", "React.js"],
    description: "Professional accounting services platform for an international client.",
    features: ["Minimal UI design", "Service-focused content", "SEO optimization", "Contact integration"],
    imageUrl: "",
  },
  {
    id: "work-amarjyoti",
    title: "Amar Jyoti Upload System",
    category: "Tools",
    url: "https://amarjyoti-flax.vercel.app/upload",
    tech: ["React.js", "Node.js", "Cloud Storage"],
    description: "Secure document upload system for managing user submissions.",
    features: ["Secure file upload", "Backend storage integration", "Input validation", "Lightweight UI"],
    imageUrl: "",
  },
  {
    id: "work-zforce",
    title: "ZForce EV",
    category: "EV",
    url: "https://www.zforceev.com/",
    tech: ["Next.js", "React.js"],
    description: "Visually engaging EV platform showcasing next-generation electric mobility.",
    features: ["Interactive product showcase", "Smooth animations", "Responsive UI", "Performance-optimized frontend"],
    imageUrl: "",
  },
  {
    id: "work-luxury-bus",
    title: "Luxury Bus Rental",
    category: "Travel",
    url: "https://www.luxurybusrental.in/",
    tech: ["React.js", "Node.js"],
    description: "Lead-generation platform for luxury transportation services.",
    features: ["Booking and inquiry system", "Service listings", "Mobile-optimized UI", "Conversion-focused layout"],
    imageUrl: "",
  },
  {
    id: "work-derxo",
    title: "Derxo Platform",
    category: "SaaS",
    url: "https://www.derxo.com/",
    tech: ["Next.js", "Node.js"],
    description: "Scalable SaaS platform with modular architecture and API-driven data handling.",
    features: ["API-driven architecture", "Clean scalable UI", "Modular frontend", "Optimized performance"],
    imageUrl: "",
  },
  {
    id: "work-true-hospitals",
    title: "True Hospitals",
    category: "Healthcare",
    url: "https://truehospitals.com/",
    tech: ["React.js", "Next.js"],
    description: "Healthcare platform to streamline patient interaction and present hospital services.",
    features: ["Department listings", "Patient information pages", "Responsive UI", "Accessible design"],
    imageUrl: "",
  },
  {
    id: "work-zentrosure",
    title: "Zentrosure",
    category: "Insurance",
    url: "https://zentrosure.com/",
    tech: ["Node.js", "React.js", "MySQL"],
    description: "Insurance-tech platform for policy listings and user interactions.",
    features: ["Insurance product management", "Secure backend", "API integrations", "Scalable architecture"],
    imageUrl: "",
  },
  {
    id: "work-cashivanand",
    title: "Cashivanand",
    category: "Finance",
    url: "https://cashivanand.com/",
    tech: ["React.js", "Node.js"],
    description: "Financial services platform with clean UI and lead generation.",
    features: ["Financial service presentation", "Lead generation", "Clean minimal UI", "SEO-friendly architecture"],
    imageUrl: "",
  },
  {
    id: "work-zentroverse",
    title: "Zentroverse",
    category: "Enterprise",
    url: "https://www.zentroverse.com",
    tech: ["React.js", "Node.js", "AWS", "DevOps"],
    description: "Large-scale enterprise platform with multiple modules and role-based access.",
    features: ["Multi-module architecture", "Role-based access", "Scalable backend", "API automation"],
    imageUrl: "",
  },
  {
    id: "work-neuro-vihar",
    title: "Neuro Vihar Digital",
    category: "Healthcare",
    url: "https://neuro-vihar-digital-58.vercel.app/",
    tech: ["Next.js", "React.js"],
    description: "Modern healthcare interface focusing on usability, performance, and clean design.",
    features: ["Responsive UI", "Fast performance", "Clean interface", "Structured content delivery"],
    imageUrl: "",
  },
  {
    id: "work-dummy-test",
    title: "Zentroverse Demo Portal (Test)",
    category: "SaaS",
    url: "https://www.zentroverse.com",
    tech: ["React.js", "Node.js", "MongoDB", "Vite"],
    description: "Dummy test project to verify Our Work CMS and /works page integration.",
    features: ["CMS-driven cards", "Live screenshot fallback", "Admin publish", "Public /works grid"],
    imageUrl: "",
  },
];
